spring.application.name=studium-api

#Postgres Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


#JWT token
studium.token.key=${TOKEN_SIGNATURE}
token.expiration.time=900000
refreshtoken.expiration.time=604800000

#Redis configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379

