spring.application.name=studium-api

#vercel

#Postgres Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# Disable prepared statements ? not supported in transaction mode pooler (For deployment)
spring.datasource.hikari.connection-init-sql=SET SESSION CHARACTERISTICS AS TRANSACTION ISOLATION LEVEL READ COMMITTED
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true


# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


#JWT token
studium.token.key=${TOKEN_SIGNATURE}
token.expiration.time=${TOKEN_EXPIRATION}
refreshtoken.expiration.time=${REFRESH_TOKEN_EXPIRATION}

#Redis configuration
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

#Cookies configuration
jwt.cookie.name=JWT-TOKEN
jwt.cookie.max-age=3600
jwt.cookie.secure=false
jwt.cookie.domain=
jwt.refresh.cookie.name=REFRESH-TOKEN
jwt.refresh.cookie.max-age=604800

#Logging for testing
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG



